### ISSUE TITLE
Add License.md

### ISSUE THREAD

**Issue by vikramnr** [IamManchanda/algorithms-javascript#13]

**Comment by IamManchanda** [comment]
Yeah sure will add ... Currently out from system but feel free to use it with MIT based licensing freedom :)

**Comment by IamManchanda** [comment]
I have added it https://github.com/IamManchanda/algorithms-javascript/commit/3cbbd92b1e00b7fac0821a0b894c4ed8d22e94e2

Closing this thread. Thanks @vikramnr
